# -*- coding: utf-8 -*-
"""Tiny Data Analysis Project: Disney+

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HrEijmwiSoZQS_XMJ8AfBpGq-7eg1EPM
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

"""Import the following package ``gdown`` to download files from Google Drive."""

import gdown

url = "https://drive.google.com/u/1/uc?id=118sEZB_-OfyXH130f-EED4KI26AXH8FO&export=download"
# mirror_url = "https://drive.google.com/u/1/uc?id=1xlzqH8z2ChAO4xPpm3GDfslyni53Bn5j&export=download"
output = "disney_plus_titles.csv"
gdown.download(url, output)

df_d = pd.read_csv(output)

m, n = df_d.shape
print(f"Size of dataset: {m}")
print(f"Number of Features: {n}")

df_d.head()

"""# **This project aims to explore the changes in the distribution of video content ratings on streaming platforms over different eras, analyze potential reasons for these changes, and make predictions about future trends.**

Initially, we segmented the content based on "suitability for children" and observed that from the 1920s to the 1960s, the proportion of movies deemed unsuitable for children increased annually. From 1980 to 2020, this percentage surged by nearly 60 percentage points, **indicating a growing trend of diversification and openness in contemporary film and television content creation.**
"""

#Content suitable for children
df_d['twenty_year_interval'] = (df_d['release_year'] // 20) * 20

selected_ratings = ['G', 'PG', 'TV-Y', 'TV-Y7', 'TV-G']
filtered_df = df_d[df_d['rating'].isin(selected_ratings)]

rating_counts = filtered_df.groupby('twenty_year_interval').size()

total_all_ratings = df_d.groupby('twenty_year_interval').size()

ratios = rating_counts.div(total_all_ratings) * 100

ratios.plot(kind='line', marker='o', figsize=(15, 6))
plt.title("Rating Trend of content appropriate for kids in Different Twenty-Year")
plt.xlabel('Twenty-Year Interval')
plt.ylabel('Percentage')
plt.show()

#Movie content unsuitable for children
df_d['twenty_year_interval'] = (df_d['release_year'] // 20) * 20

selected_ratings = ['PG-13', 'R', 'NC-17', 'TV-PG', 'TV-14', 'TV-MA']
filtered_df = df_d[df_d['rating'].isin(selected_ratings)]

rating_counts = filtered_df.groupby('twenty_year_interval').size()

total_all_ratings = df_d.groupby('twenty_year_interval').size()

ratios = rating_counts.div(total_all_ratings) * 100

ratios.plot(kind='line', marker='o', figsize=(15, 6))
plt.title("Rating Trend of content inappropriate for kids in Different Twenty-Year")
plt.xlabel('Twenty-Year Interval')
plt.ylabel('Percentage')
plt.show()

"""Subsequently, we analyzed the distribution of movie and TV ratings across different eras. Regarding movies, the proportion of G-rated films suitable for all age groups has decreased over the years. Parents should be particularly attentive to PG-13-rated content, which is unsuitable for children under 13, as it has steadily increased. **In the 1940s, there was a significant gap of nearly 100% between G and PG-13 ratings, but today both ratings account for approximately 30%, with a negligible difference.**"""

df_d['decade'] = (df_d['release_year'] // 20) * 20

selected_ratings = ['G', 'PG', 'PG-13', 'R', 'NC-17']
movies_df = df_d[df_d['rating'].isin(selected_ratings)]

movies_rating_counts = movies_df.groupby(['decade', 'rating']).size().unstack(fill_value=0)

total_movies_per_decade = movies_rating_counts.sum(axis=1)

movie_rating_percentages = movies_rating_counts.div(total_movies_per_decade, axis=0) * 100

movie_rating_percentages.plot(kind='line', marker='o', figsize=(15, 6))
plt.title("Movie Rating Trend in Different Decades")
plt.xlabel('Decade')
plt.ylabel('Percentage')
plt.legend(title='Rating', bbox_to_anchor=(1, 1))

plt.show()

"""In terms of TV program ratings, categories like **TV-Y7 and TV-G, suitable for young children and all age groups, show a decline, with decreases of 40% and 20%, respectively.** On the other hand, **TV-PG and TV-14, ratings inappropriate for children, have increased by approximately 40 and 30 percentage points.**"""

df_d['decade'] = (df_d['release_year'] // 20) * 20

selected_ratings = ['TV-Y', 'TV-Y7', 'TV-G', 'TV-PG', 'TV-14', 'TV-MA']
TV_df = df_d[df_d['rating'].isin(selected_ratings)]

TV_rating_counts = TV_df.groupby(['decade', 'rating']).size().unstack(fill_value=0)


total_TV_per_decade = TV_rating_counts.sum(axis=1)


TV_rating_percentages = TV_rating_counts.div(total_TV_per_decade, axis=0) * 100


TV_rating_percentages.plot(kind='line', marker='o', figsize=(15, 6))
plt.title("TV Rating Trend in Different Decades")
plt.xlabel('Decade')
plt.ylabel('Percentage')
plt.legend(title='Rating', bbox_to_anchor=(1, 1))


plt.show()

"""From the above chart analysis, it is evident that **producers of TV shows and movies have gradually shifted away from conservative cultural and content limitations. Producing exclusively family-friendly content is no longer sufficient to captivate audiences.** The competition among various genres has intensified due to this trend, with each type of content having its own set of supporters.

I believe that this trend, which has developed over the past few decades, has reached a point of equilibrium. Considering that most subscribers to streaming platforms are adults, **the current rating distribution is likely to persist.** If directors and creators aspire to succeed on streaming platforms, they should **not only focus on the content but also consider the diversity and distinctiveness of the themes** to stand out in this era of abundant choices.
"""